AllCops:
  TargetRubyVersion: 2.5
  Exclude:
  - 'bin/*'
  - 'config/initializers/simple_form*.rb'
  - 'db/schema.rb'

Bundler/OrderedGems:
  Exclude:
    - 'Gemfile'

Style/ClassAndModuleChildren:
  Exclude:
    - 'test/test_helper.rb'

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'app/helpers/application_helper.rb'
    - 'app/mailers/application_mailer.rb'
    - 'app/models/application_record.rb'
    - 'config/application.rb'

Metrics/LineLength:
  Max: 180

Rails:
  Enabled: true
