inherit_mode:
  merge:
  - Exclude

plugins:
- rubocop-performance
- rubocop-rails
- rubocop-capybara
- standard-custom

inherit_gem:
  standard: config/base.yml
  standard-custom: config/base.yml
  standard-performance: config/base.yml

AllCops:
  Exclude:
  - 'bin/*'
  - 'config/initializers/simple_form*.rb'
  - 'db/schema.rb'
  NewCops: enable

Capybara/ClickLinkOrButtonStyle:
  EnforcedStyle: strict

Layout/SpaceInsidePercentLiteralDelimiters:
  Exclude:
  - Gemfile

Layout/ExtraSpacing:
  AllowForAlignment: true

Layout/SpaceInsideArrayLiteralBrackets:
  Exclude:
  - config/environments/production.rb

Style/GlobalStdStream:
  Exclude:
  - config/environments/production.rb

Rails:
  Enabled: yes
