AllCops:
  TargetRubyVersion: 2.5
  Exclude:
  - 'bin/*'
  - 'config/initializers/simple_form*.rb'
  - 'db/schema.rb'

Bundler/OrderedGems:
  Exclude:
    - 'Gemfile'

Style/ClassAndModuleChildren:
  Exclude:
    - 'test/test_helper.rb'

Style/Documentation:
  Exclude:
    - 'db/**/*'
    - 'spec/**/*'
    - 'test/**/*'
    - 'app/helpers/application_helper.rb'
    - 'app/mailers/application_mailer.rb'
    - 'app/models/application_record.rb'
    - 'config/application.rb'

Metrics/AbcSize:
  Enabled: false

Metrics/LineLength:
  Max: 180

Metrics/MethodLength:
  Max: 100

Performance/RedundantMerge:
  Exclude:
    - config/initializers/rollbar.rb

Rails:
  Enabled: true

Style/IfUnlessModifier:
  Enabled: false

Style/Lambda:
  Enabled: false
