require:
- rubocop-performance
- rubocop-rails

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
  - 'bin/*'
  - 'config/initializers/simple_form*.rb'
  - 'db/schema.rb'

Bundler/OrderedGems:
  Exclude:
    - 'Gemfile'

Style/ClassAndModuleChildren:
  Exclude:
    - 'test/test_helper.rb'

Style/Documentation:
  Exclude:
    - 'db/**/*'
    - 'spec/**/*'
    - 'test/**/*'
    - 'app/*/application_*.rb'
    - 'app/controllers/*.rb'
    - 'config/application.rb'

Metrics/AbcSize:
  Enabled: false

Layout/LineLength:
  Max: 180

Metrics/MethodLength:
  Max: 100

Performance/RedundantMerge:
  Exclude:
    - config/initializers/rollbar.rb

Rails:
  Enabled: true

Style/AccessModifierDeclarations:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
