inherit_mode:
  merge:
  - Exclude

require:
- rubocop-performance
- rubocop-rails
- rubocop-capybara
- standard/cop/block_single_line_braces

inherit_gem:
  standard: config/base.yml

AllCops:
  Exclude:
  - 'bin/*'
  - 'config/initializers/simple_form*.rb'
  - 'db/schema.rb'
  NewCops: enable

Layout/SpaceInsidePercentLiteralDelimiters:
  Exclude:
  - Gemfile

Layout/ExtraSpacing:
  AllowForAlignment: true

Layout/SpaceInsideArrayLiteralBrackets:
  Exclude:
  - config/environments/production.rb

Style/GlobalStdStream:
  Exclude:
  - config/environments/production.rb

Rails:
  Enabled: yes
