inherit_mode:
  merge:
  - Exclude

require:
- rubocop-performance
- rubocop-rails
- standard/cop/semantic_blocks

inherit_gem:
  standard: config/base.yml

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
  - 'bin/*'
  - 'config/initializers/simple_form*.rb'
  - 'db/schema.rb'
