language: ruby

addons:
  postgresql: "9.6"
  apt:
    packages:
    - postgresql-9.6-postgis-2.3

env:
  - DATABASE_URL=postgis://postgres@localhost/travis_ci_test

cache: bundler

script:
- bundle exec rails db:setup
- bundle exec rails test
