# syntax=docker/dockerfile:1
FROM ruby:3.3.11
ENV LANG C.UTF-8
RUN rm -f /etc/apt/apt.conf.d/docker-clean; echo 'Binary::apt::APT::Keep-Downloaded-Packages "true";' > /etc/apt/apt.conf.d/keep-cache
RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
 --mount=type=cache,target=/var/lib/apt,sharing=locked \
 apt-get update && apt-get install -y ca-certificates curl gnupg
RUN mkdir /app
WORKDIR /app
