---
services:
  db:
    image: postgis/postgis:latest
    volumes:
    - db-data:/var/lib/postgresql/data:cached
    environment:
      POSTGRES_PASSWORD: mysecretpassword
  web:
    build:
      context: .
      dockerfile: Dockerfile.local
    command: bundle exec rails s -p 7379 -b 0.0.0.0
    volumes:
    - .:/app:cached
    - dot-bundle:/app/.bundle
    - bundle-cache:/usr/local/bundle
    # exclude
    - /app/tmp
    tmpfs:
    - /app/tmp/pids
    ports:
    - "7379:7379"
    depends_on:
    - db
    environment:
      DATABASE_URL: postgis://postgres:mysecretpassword@db:5432
      BUNDLE_AUTO_INSTALL: true
volumes:
  db-data:
  dot-bundle:
  bundle-cache:
