---
version: '3'
services:
  db:
    image: mdillon/postgis:10-alpine
    volumes:
    - db-data:/var/lib/postgresql/data:cached
    environment:
      POSTGRES_PASSWORD: mysecretpassword
  web:
    build:
      context: .
      dockerfile: Dockerfile.local
    command: bundle exec rails s -p 7379 -b 0.0.0.0
    volumes:
    - code:/app:cached
    - dot-bundle:/app/.bundle
    - bundle-cache:/usr/local/bundle
    # exclude
    - /app/tmp
    tmpfs:
    - /app/tmp/pids
    ports:
    - "7379:7379"
    depends_on:
    - db
    environment:
      DATABASE_URL: postgis://postgres:mysecretpassword@db:5432
volumes:
  db-data:
  dot-bundle:
  bundle-cache:
  code:

x-mutagen:
  sync:
    defaults:
      ignore:
        vcs: true
    code:
      alpha: "./"
      beta: "volume://code"
      mode: two-way-resolved
      ignore:
        paths:
        - "log/*"
        - "tmp/*"
    log:
      alpha: "volume://code/log"
      beta: "./log/"
      mode: two-way-resolved
