name: CI
on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-20.04

    services:
      postgres:
        image: postgis/postgis:latest
        env:
          POSTGRES_PASSWORD: cisecretpassword
          POSTGRES_DB: ci_test_db
        ports:
        - 5432:5432
        options: >-
          --health-cmd="pg_isready" --health-interval=10s --health-timeout=5s --health-retries=5

    env:
      DATABASE_URL: "postgis://postgres:cisecretpassword@localhost:5432/ci_test_db"

    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - run: bundle exec rails db:setup
    - run: bundle exec rails test
    - run: bundle exec rubocop --enable-pending-cops
