name: CI
on: push

jobs:
  test:
    runs-on: ubuntu-20.04

    services:
      postgres:
        image: mdillon/postgis:10-alpine
        env:
          POSTGRES_PASSWORD: cisecretpassword
          POSTGRES_DB: ci_test_db
        ports:
        - 5432:5432
        options: >-
          --health-cmd="pg_isready" --health-interval=10s --health-timeout=5s --health-retries=5

    env:
      DATABASE_URL: "postgis://postgres:cisecretpassword@localhost:5432/ci_test_db"

    steps:
    - uses: actions/checkout@v2
    - run: bundle exec rails db:setup
    - run: bundle exec rails test
    - run: bundle exec rubocop --enable-pending-cops
