name: Update rubocop gems
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v4.1.1
    - name: git config
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

    - uses: ruby/setup-ruby@89f90524b88a01fe6e0b732220432cc6142926af # v1.313.0
      with:
        bundler-cache: true
    - run: |
        set -euxo pipefail
        bundle update $(bundle list --name-only | grep rubocop)
        git status
        git diff
    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
      with:
        add-paths: |
          Gemfile.lock
    - name: Check outputs
      if: ${{ steps.cpr.outputs.pull-request-number }}
      run: |
        echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
        echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
